In [11]:
import numpy as np
a=np.array([1,2,3])
print("one dimensional array a=",a)
b=np.array([1,2,3])
print("two dimensional array a=",b)
print("size of the array:",a.shape)
print("element at indices 0,1,2:",a[0],a[1],a[2])
a[0]=5
print("array after changing the element at index 0:",a)
a=np.zeros((2,2))
print("an array of all zeros:\n",a)
b=np.ones((1,2))
print("an array of all ones:\n",b)
c=np.full((2,2),7)
print("a constant array:\n",c)
d=np.eye(2)
print("A 2*2 identity matrix\n:",d)
e=np.random.random((2,2))
print(" an array with random values :",e)


one dimensional array a= [1 2 3]
two dimensional array a= [1 2 3]
size of the array: (3,)
element at indices 0,1,2: 1 2 3
array after changing the element at index 0: [5 2 3]
an array of all zeros:
 [[0. 0.]
 [0. 0.]]
an array of all ones:
 [[1. 1.]]
a constant array:
 [[7 7]
 [7 7]]
A 2*2 identity matrix
: [[1. 0.]
 [0. 1.]]
 an array with random values : [[0.23614868 0.15973419]
 [0.30831233 0.70822779]]


In [15]:
import numpy as np
print("array indexing slicing")
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("al=",a1)
b=a1[:2,1:3]
print("subaray consisting of first rows and columns 1 and 2\n:",b)
b=a1[:2,1:3]
print("subarray consist of second rows:",b)
print("assessing columns:")
b=a1[:,1]
print(b,b.shape)
c=a1[:,1:2]
print(c,c.shape)
print("array integer indexing:")
a2=np.array([[1,2],[3,4],[5,6]])
print("a2=",a2)
print("example of array integer indexing :",a2[[0,1,2],[0,1,0]])
print(a2[[0,0],[1,1]])
print(np.array([a2[0,1],a[0,1]]))
a3=a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a3=",a3)
b=np.array([0,2,0,1])
print("b=",b)
print("a3 =",a3[np.arange(4),b])
a3[np.arange(4),b]+=10
print("a3=",a3)
print("boolean array indexing:")
a= np.array([[1,2],[3,4],[5,6]])
print("a=",a)
bool_idx=(a>2)
print("element greater than 2:",a[bool_idx])

array indexing slicing
al= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
subaray consisting of first rows and columns 1 and 2
: [[2 3]
 [6 7]]
subarray consist of second rows: [[2 3]
 [6 7]]
assessing columns:
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
array integer indexing:
a2= [[1 2]
 [3 4]
 [5 6]]
example of array integer indexing : [1 4 5]
[2 2]
[2 2]
a3= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b= [0 2 0 1]
a3 = [ 1  6  7 11]
a3= [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
boolean array indexing:
a= [[1 2]
 [3 4]
 [5 6]]
element greater than 2: [3 4 5 6]


In [21]:
import numpy as n
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[6,9],[4,4]],dtype=np.float64)
print("x=",x)
print("y=",y)
print("element wise addition :",np.add(x,x))
print("element wise subtraction:",np.subtract(x,y))
print("element wise multiplication:",np.multiply(x,y))
print("element wise square root of x:",np.sqrt(x))
print("matrix multipliaction:",np.dot(x,y))
print("sum of all element of matix x:",np.sum(x))
print("sum of element in each column of matrix y:",np.sum(y,axis=0))
print("sum of elements in each row of matrix y:",np.sum(y,axis=1))
print("transpose of matrix x:",x.T)      

x= [[1. 2.]
 [3. 4.]]
y= [[6. 9.]
 [4. 4.]]
element wise addition : [[2. 4.]
 [6. 8.]]
element wise subtraction: [[-5. -7.]
 [-1.  0.]]
element wise multiplication: [[ 6. 18.]
 [12. 16.]]
element wise square root of x: [[1.         1.41421356]
 [1.73205081 2.        ]]
matrix multipliaction: [[14. 17.]
 [34. 43.]]
sum of all element of matix x: 10.0
sum of element in each column of matrix y: [10. 13.]
sum of elements in each row of matrix y: [15.  8.]
transpose of matrix x: [[1. 3.]
 [2. 4.]]


In [27]:
import numpy as np
print("example for broadcasting:")
v=np.array([1,2,3])
w=np.array([4,5])
print("v=",v)
print("w=",w)
print("outer product of above vectors:")
print(np.reshape(v,(3,1))*w)
x=(np.array([[1,2,3],[4,5,6]]))
print("x=",x)
print("resultant matrix after adding the vector x to each row of matrix v :")
print(x+v)
print("example for broadcasting fails:")
print("adding the vector x to each column of matrix w will generate an error ")
print("solutiin :reshape the matrix w then result will be:")
print(x+np.reshape(w,(2,1)))

example for broadcasting:
v= [1 2 3]
w= [4 5]
outer product of above vectors:
[[ 4  5]
 [ 8 10]
 [12 15]]
x= [[1 2 3]
 [4 5 6]]
resultant matrix after adding the vector x to each row of matrix v :
[[2 4 6]
 [5 7 9]]
example for broadcasting fails:
adding the vector x to each column of matrix w will generate an error 
solutiin :reshape the matrix w then result will be:
[[ 5  6  7]
 [ 9 10 11]]
